export const SUPPORTED_BRANCHES = [
  "COMPUTER SCIENCE AND ENGINEERING",
  "INFORMATION SCIENCE AND ENGINEERING",
  "ARTIFICIAL INTELLIGENCE AND DATA SCIENCE",
  "ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING",
  "ELECTRONICS AND COMMUNICATION ENGG",
  "ELECTRICAL & ELECTRONICS ENGINEERING",
  "MECHANICAL ENGINEERING",
  "CIVIL ENGINEERING",
  "INFORMATION TECHNOLOGY",
  "COMPUTER SCIENCE AND BUSINESS SYSTEMS",
  "COMPUTER SCIENCE AND ARTIFICIAL INTELLIGENCE",
  "COMPUTER SCIENCE (CYBER SECURITY)",
  "COMPUTER SCIENCE (DATA SCIENCE)",
  "COMPUTER SCIENCE (CLOUD COMPUTING)",
  "ROBOTICS AND ARTIFICIAL INTELLIGENCE"
];